[build]
  command = "pnpm build"
  publish = "app/build"
  functions = "backend/functions"

# This will make it so that everything serves on 4317 and proxies to the SvelteKit dev server on :4320
[dev]
  command = "pnpm dev:app"
  framework = "#custom"
  port = 4317
  targetPort = 4320
  # Determines if the web page opens automatically in the browser when it starts up
  autoLaunch = true

[[headers]]
  for = "/**"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"

[[redirects]]
  from = "/api/oauth/start"
  to = "/.netlify/functions/oauth-start"
  status = 200

[[redirects]]
  from = "/api/oauth/callback"
  to = "/.netlify/functions/oauth-callback"
  status = 200

[[redirects]]
  from = "/api/token"
  to = "/.netlify/functions/token"
  status = 200